name: CI

# Trigger this workflow on individual pull requests and merge groups that target the `main` branch
on:
  pull_request:
  merge_group:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'merge_group' && github.event.merge_group.head_sha || github.event.pull_request.head.sha }}
      - id: get_commit_message
        run: echo ${{ github.event.pull_request.commits[0].message }} "commit_message=$(git show -s --format=%s)" >> $GITHUB_OUTPUT
      - id: random
        run: echo "number=$(( ( RANDOM % 50 )  + 10 ))" >> $GITHUB_OUTPUT
      - name: 😴 sleep ${{ steps.random.outputs.number }}s
        if: github.event_name == 'pull_request'
        run: sleep ${{ steps.random.outputs.number }}
      - name: Fail
        if: ${{ github.event_name == 'merge_group' && contains(steps.get_commit_message.outputs.commit_message, 'fail') }}
        run: exit 1
