name: CI

# Trigger this workflow on individual pull requests and merge groups that target the `main` branch
on:
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: echo "number=$(( ( RANDOM % 60 )  + 10 ))" >> $GITHUB_ENV
      - name: 😴 sleep ${{ steps.random.outputs.number }}s
        # if: github.event_name == 'pull_request'
        run: sleep ${{ steps.random.outputs.number }}
      - run: echo "Done"
