name: CI

# Trigger this workflow on individual pull requests and merge groups that target the `main` branch
on:
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 😴 sleep
        # if: github.event_name == 'pull_request'
        run: sleep $(( ( RANDOM % 60 )  + 10 ))
      - run: echo "Done"
