name: CI

# Trigger this workflow on individual pull requests and merge groups that target the `main` branch
on:
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - id: get_commit_message
        run: echo "commit_message=$(git show -s --format=%s)" >> $GITHUB_OUTPUT
      - id: random
        run: echo "number=$(( ( RANDOM % 50 )  + 10 ))" >> $GITHUB_OUTPUT
      - name: 😴 sleep ${{ steps.random.outputs.number }}s
        if: github.event_name == 'pull_request'
        run: sleep ${{ steps.random.outputs.number }}
      - name: Fail
        if: ${{ github.event_name == 'merge_group' && contains(steps.get_commit_message.outputs.commit_message, 'fail') }}
        run: exit 1
