name: Create PR

on:
  workflow_call:
    inputs:
      file_name:
        description: "The name of the file to be created"
        default: "DATA.txt"
        required: true
        type: string
      file_content:
        description: "The content of the file to be created"
        default: "Hello World!"
        required: false
        type: string
      pr_title:
        description: "The title of the PR"
        required: false
        type: string
      pr_body:
        description: "The body of the PR"
        default: "This PR was automatically created!"
        required: false
        type: string
      branch_name:
        description: "The name of the new PR branch"
        required: false
        type: string
  workflow_dispatch:
    inputs:
      file_name:
        description: "The name of the file to be created"
        default: "DATA.txt"
        required: true
        type: string
      file_content:
        description: "The content of the file to be created"
        default: "Hello World!"
        required: false
        type: string
      pr_title:
        description: "The title of the PR"
        required: false
        type: string
      pr_body:
        description: "The body of the PR"
        default: "This PR was automatically created!"
        required: false
        type: string
      branch_name:
        description: "The name of the new PR branch"
        required: false
        type: string

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ inputs.file_content }}" > ${{ inputs.file_name }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ inputs.branch_name && inputs.branch_name || format('patch-{0}', inputs.file_name) }}
          create_branch: true
      - run: gh pr create --title "${{ inputs.pr_title && inputs.pr_title || format('Created {0}', inputs.file_name) }}" --body "${{ inputs.pr_body }}"
        env:
          GH_TOKEN: ${{ github.token }}
