name: Create PR

on:
 workflow_dispatch:
   inputs:
     file_name:
       default: "DATA.txt" 
       required: true
       type: string
     file_content:
       default: "Hello World!"
       required: false
       type: string
     pr_title:
       required: false
       type: string
     pr_body:
       default: "This PR was automatically created!"
       required: false
       type: string
     branch_name:
       default: "patch"
       required: false
       type: string
 workflow_call:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.file_content }}" > ${{ inputs.file_name }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           branch: ${{ branch_name }}
           create_branch: true
      - run: gh pr create --title "${{ inputs.pr_title && inputs.pr_title || 'Created ' + inputs.pr_title }}" --body "${{ inputs.pr_body }}"
        env:
          GH_TOKEN: ${{ github.token }}

