name: Create PR

on:
 workflow_dispatch:
   inputs:
     file-name:
       default: "thiswillfail" 
       required: true
       type: string
     file-content:
       default: "Hello MQ demo runner"
       required: false
       type: string
 workflow_call:
   inputs:
     file-name:
       default: "thiswillfail" 
       required: true
       type: string
     file-content:
       default: "Hello MQ demo runner"
       required: false
       type: string
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ inputs.file-content }} > ${{ inputs.file-name }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           branch: actions-bot-${{ inputs.file-name }}-patch-6
           create_branch: true
      - run: gh pr create --title "${{ inputs.file-name }} PR" --body "${{ inputs.file-name }} body"
        env:
          GH_TOKEN: ${{ github.token }}

