name: Demo Conflict PRs

on:
  workflow_dispatch:

jobs:
  demo:
    name: Conflict
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_name: ['File1.txt']
        file_content: ['Hello World!', 'Hello Mars!']
    steps:
    - uses: actions/checkout@v3
    - uses: octodemo/mq-demo/.github/actions/create-pr@main
      with:
        file_name: ${{ matrix.file_name }}
        file_content: ${{ matrix.file_content }}
        token: ${{ secrets.AUSTEN_PAT }}
  # demo:
  #   name: Conflict
  #   strategy:
  #     matrix:
  #       file_name: ['File1.txt']
  #       file_content: ['Hello World!', 'Hello Mars!']
  #   uses: octodemo/mq-demo/.github/workflows/create-pr.yml@main
  #   with:
  #     file_name: ${{ matrix.file_name }}
  #     file_content: ${{ matrix.file_content }}
  #   secrets:
  #     TOKEN: ${{ secrets.AUSTEN_PAT }}
  # merge:
  #   name: Merge
  #   needs: demo
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: gh pr merge ${{ needs.demo.outputs.pr_number }}
  #       env:
  #         GH_TOKEN: ${{ secrets.AUSTEN_PAT }}